[tool.poetry]
name = "OntoAligner"
version = "1.0.0"
description = "OntoAligner is a user-friendly Python library designed to simplify the process of ontology alignment/matching."
authors = ["Hamed Babaei Giglou <hamedbabaeigiglou@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://ontoaligner.readthedocs.io/"
repository = "https://github.com/sciknoworg/OntoAligner/"

[tool.poetry.dependencies]
python = ">=3.9"
pathlib = "*"
argparse = "*"
owlready2 = "*"
rdflib = "*"
tqdm = "*"
ontospy = "*"
numpy = "*"
torch = "*"
contextlib = "*"
transformers = "*"
datasets = "*"
rapidfuzz = "*"
openai = "*"
rank_bm25 = "*"
sklearn = "*"
sentence-transformers = "*"
setfit = "*"

[tool.poetry.dev-dependencies]
ruff = "*"
pre-commit = "*"
setuptools = "*"
wheel = "*"
twine = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
